#!/usr/bin/env bash

set -e

N=1
if [[ $1 ]]; then
    N=$1
fi

RECENT=$(gdrive list --no-header | head -n $N | tail -1)
ID=$(echo $RECENT | cut -f 1 -d " ")
# Piping to xargs is a neat trick to trim whitespace
TITLE=$(gdrive info $ID | grep "Name: " | cut -f 2 -d ":" | xargs)

echo "https://drive.google.com/uc?export=download&id=${ID}" | pbcopy

echo "Link to ${TITLE} copied to clipboard"
