#!/usr/bin/env bash

APIKEY=$(cat ~/.octoprint/apikey)
HOST=$(cat ~/.octoprint/host)

USAGE=$(cat <<EOF
$(basename $0) [ --host HOST ] [ -v | --verbose ] [ --timelapse ] [ --fps FPS ] [ --interval INTERVAL ] [ --post-roll POSTROLL ] FILE | status
EOF
)

FPS=10
INTERVAL=10
POST_ROLL=5
while [[ "$1" != "" ]]; do
   case "$1" in
       "--help" | "-h")
         echo "$USAGE"
         exit 0
         ;;
       "--host")
         shift
         HOST=$1
         ;;
       "--timelapse")
         TIMELAPSE=yes
         ;;
       "--interval")
         shift
         TIMELAPSE=yes
         INTERVAL=$1
         ;;
       "--fps" )
         shift
         TIMELAPSE=yes
         FPS=$1
         ;;
       "--post-roll" )
         shift
         TIMELAPSE=yes
         POST_ROLL=$1
         ;;
       "-v" | "--verbose")
         VERBOSE=yes
         set -x
         ;;
       *)
         if [[ $1 =~ ^- ]]
         then
             echo "Unrecognized option $1"
             echo $USAGE
             exit 1
         fi

         INPUTFILE="$1"
         ;;
   esac
   shift
done

URL=http://${HOST}

CURL_OPTIONS=$(if [[ -n $VERBOSE ]]; then echo "-i"; fi)

if [[ -z $INPUTFILE ]]
then
    echo "You must specify a file to send."
    exit 1
fi

if [[ ! -z $TIMELAPSE ]]
then
    echo "Enabling timelapse"
    curl $CURL_OPTIONS \
         --silent \
         -X POST \
         -H "X-Api-Key: ${APIKEY}" \
         -H "Content-Type: application/json" \
         $URL/api/timelapse \
         -d @- \
         <<EOF
{
  "type" : "timed",
  "postRoll" : $POST_ROLL,
  "fps" : $FPS,
  "interval" : $INTERVAL
}
EOF
fi

if [[ "$INPUTFILE" == "status" ]]
then
  curl $CURL_OPTIONS \
       --silent \
       -H "X-Api-Key: ${APIKEY}" \
       -H "Content-Type: application/json" \
       "$URL/api/printer"
else
  TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
  FILENAME="$(basename "$INPUTFILE" .gcode)-$TIMESTAMP.gcode"

  echo "Uploading $INPUTFILE to $URL as $FILENAME"

  curl $CURL_OPTIONS -H "X-Api-Key:${APIKEY}" -F "file=@${INPUTFILE};filename=${FILENAME}" $URL/api/files/local

  echo "Printing $FILENAME"

  curl $CURL_OPTIONS \
       -X POST \
       -H "X-Api-Key: ${APIKEY}" \
       -H "Content-Type: application/json" \
       $(echo "$URL/api/files/local/${FILENAME}" | tr " " "_") \
       -d @- \
       <<EOF
{
  "command" : "select",
  "print" : true
}
EOF

fi
