#!/usr/bin/env bash

APIKEY=$(cat ~/.octoprint/apikey)
URL=$(cat ~/.octoprint/url)

USAGE=$(cat <<EOF
$(basename $0) [ -v | --verbose ] [ --timelapse ] FILE
EOF
)

while [[ "$1" != "" ]]; do
   case "$1" in
       "--help" | "-h")
         echo "$USAGE"
         exit 0
         ;;
       "--timelapse")
         TIMELAPSE=yes
         ;;
       "-v" | "--verbose")
         VERBOSE=yes
         set -x
         ;;
       *)
         if [[ $1 =~ ^- ]]
         then
             echo "Unrecognized option $1"
             echo $USAGE
             exit 1
         fi

         FILENAME=$1
         ;;
   esac
   shift
done

CURL_OPTIONS=$(if [[ -n $VERBOSE ]]; then echo "-i"; fi)

if [[ -z $FILENAME ]]
then
    echo "You must specify a file to send."
    exit 1
fi

if [[ ! -z $TIMELAPSE ]]
then
    echo "Enabling timelapse"
    curl $CURL_OPTIONS \
         -X POST \
         -H "X-Api-Key: ${APIKEY}" \
         -H "Content-Type: application/json" \
         $URL/api/timelapse \
         -d @- \
         <<EOF
{
  "type" : "timed",
  "postRoll" : 30,
  "fps" : 10,
  "interval" : 10
}
EOF
fi

echo "Uploading $FILENAME to $URL"

curl $CURL_OPTIONS -H "X-Api-Key:${APIKEY}" -F "file=@${FILENAME}" $URL/api/files/local

echo "Printing $FILENAME"

curl $CURL_OPTIONS \
     -X POST \
     -H "X-Api-Key: ${APIKEY}" \
     -H "Content-Type: application/json" \
     $URL/api/files/local/${FILENAME} \
     -d @- \
     <<EOF
{
  "command" : "select",
  "print" : true
}
EOF
